//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.28 at 01:41:47 PM MSD 
//


package genblaster.properties.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "AlterCodon")
public class AlterCodon {

    @XmlAttribute(name = "codon", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String codon;
    @XmlAttribute(name = "aminoacid", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String aminoacid;

    /**
     * Gets the value of the codon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodon() {
        return codon;
    }

    /**
     * Sets the value of the codon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodon(String value) {
        this.codon = value;
    }

    /**
     * Gets the value of the aminoacid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAminoacid() {
        return aminoacid;
    }

    /**
     * Sets the value of the aminoacid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAminoacid(String value) {
        this.aminoacid = value;
    }

}
