//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.28 at 01:41:47 PM MSD 
//


package genblaster.properties.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "evalue",
    "simultaniousBLASTs",
    "minORFLength",
    "maxORFLength",
    "orfPool"
})
@XmlRootElement(name = "BLAST_Properties")
public class BLASTProperties {

    @XmlElement(name = "Evalue", required = true)
    protected Evalue evalue;
    @XmlElement(name = "SimultaniousBLASTs", required = true)
    protected SimultaniousBLASTs simultaniousBLASTs;
    @XmlElement(name = "MinORFLength", required = true)
    protected MinORFLength minORFLength;
    @XmlElement(name = "MaxORFLength", required = true)
    protected MaxORFLength maxORFLength;
    @XmlElement(name = "ORFPool", required = true)
    protected ORFPool orfPool;

    /**
     * Gets the value of the evalue property.
     * 
     * @return
     *     possible object is
     *     {@link Evalue }
     *     
     */
    public Evalue getEvalue() {
        return evalue;
    }

    /**
     * Sets the value of the evalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Evalue }
     *     
     */
    public void setEvalue(Evalue value) {
        this.evalue = value;
    }

    /**
     * Gets the value of the simultaniousBLASTs property.
     * 
     * @return
     *     possible object is
     *     {@link SimultaniousBLASTs }
     *     
     */
    public SimultaniousBLASTs getSimultaniousBLASTs() {
        return simultaniousBLASTs;
    }

    /**
     * Sets the value of the simultaniousBLASTs property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimultaniousBLASTs }
     *     
     */
    public void setSimultaniousBLASTs(SimultaniousBLASTs value) {
        this.simultaniousBLASTs = value;
    }

    /**
     * Gets the value of the minORFLength property.
     * 
     * @return
     *     possible object is
     *     {@link MinORFLength }
     *     
     */
    public MinORFLength getMinORFLength() {
        return minORFLength;
    }

    /**
     * Sets the value of the minORFLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link MinORFLength }
     *     
     */
    public void setMinORFLength(MinORFLength value) {
        this.minORFLength = value;
    }

    /**
     * Gets the value of the maxORFLength property.
     * 
     * @return
     *     possible object is
     *     {@link MaxORFLength }
     *     
     */
    public MaxORFLength getMaxORFLength() {
        return maxORFLength;
    }

    /**
     * Sets the value of the maxORFLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaxORFLength }
     *     
     */
    public void setMaxORFLength(MaxORFLength value) {
        this.maxORFLength = value;
    }

    /**
     * Gets the value of the orfPool property.
     * 
     * @return
     *     possible object is
     *     {@link ORFPool }
     *     
     */
    public ORFPool getORFPool() {
        return orfPool;
    }

    /**
     * Sets the value of the orfPool property.
     * 
     * @param value
     *     allowed object is
     *     {@link ORFPool }
     *     
     */
    public void setORFPool(ORFPool value) {
        this.orfPool = value;
    }

}
