//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.28 at 01:41:47 PM MSD 
//


package genblaster.properties.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "useCluster",
    "clusterSatellites"
})
@XmlRootElement(name = "ClusterProperties")
public class ClusterProperties {

    @XmlElement(name = "UseCluster", required = true)
    protected UseCluster useCluster;
    @XmlElement(name = "ClusterSatellites", required = true)
    protected ClusterSatellites clusterSatellites;

    /**
     * Gets the value of the useCluster property.
     * 
     * @return
     *     possible object is
     *     {@link UseCluster }
     *     
     */
    public UseCluster getUseCluster() {
        return useCluster;
    }

    /**
     * Sets the value of the useCluster property.
     * 
     * @param value
     *     allowed object is
     *     {@link UseCluster }
     *     
     */
    public void setUseCluster(UseCluster value) {
        this.useCluster = value;
    }

    /**
     * Gets the value of the clusterSatellites property.
     * 
     * @return
     *     possible object is
     *     {@link ClusterSatellites }
     *     
     */
    public ClusterSatellites getClusterSatellites() {
        return clusterSatellites;
    }

    /**
     * Sets the value of the clusterSatellites property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClusterSatellites }
     *     
     */
    public void setClusterSatellites(ClusterSatellites value) {
        this.clusterSatellites = value;
    }

}
