//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.28 at 01:41:47 PM MSD 
//


package genblaster.properties.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "genBLASTerHomeDir",
    "genBLASTerDbDir",
    "roleInCluster",
    "clusterProperties",
    "distanceMatrixType",
    "blastProperties",
    "genomes"
})
@XmlRootElement(name = "GenBLASTer_Properties")
public class GenBLASTerProperties {

    @XmlElement(name = "GenBLASTer_home_dir", required = true)
    protected GenBLASTerHomeDir genBLASTerHomeDir;
    @XmlElement(name = "GenBLASTer_db_dir", required = true)
    protected GenBLASTerDbDir genBLASTerDbDir;
    @XmlElement(name = "RoleInCluster", required = true)
    protected RoleInCluster roleInCluster;
    @XmlElement(name = "ClusterProperties", required = true)
    protected ClusterProperties clusterProperties;
    @XmlElement(name = "DistanceMatrixType", required = true)
    protected DistanceMatrixType distanceMatrixType;
    @XmlElement(name = "BLAST_Properties", required = true)
    protected BLASTProperties blastProperties;
    @XmlElement(name = "Genomes", required = true)
    protected Genomes genomes;

    /**
     * Gets the value of the genBLASTerHomeDir property.
     * 
     * @return
     *     possible object is
     *     {@link GenBLASTerHomeDir }
     *     
     */
    public GenBLASTerHomeDir getGenBLASTerHomeDir() {
        return genBLASTerHomeDir;
    }

    /**
     * Sets the value of the genBLASTerHomeDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenBLASTerHomeDir }
     *     
     */
    public void setGenBLASTerHomeDir(GenBLASTerHomeDir value) {
        this.genBLASTerHomeDir = value;
    }

    /**
     * Gets the value of the genBLASTerDbDir property.
     * 
     * @return
     *     possible object is
     *     {@link GenBLASTerDbDir }
     *     
     */
    public GenBLASTerDbDir getGenBLASTerDbDir() {
        return genBLASTerDbDir;
    }

    /**
     * Sets the value of the genBLASTerDbDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenBLASTerDbDir }
     *     
     */
    public void setGenBLASTerDbDir(GenBLASTerDbDir value) {
        this.genBLASTerDbDir = value;
    }

    /**
     * Gets the value of the roleInCluster property.
     * 
     * @return
     *     possible object is
     *     {@link RoleInCluster }
     *     
     */
    public RoleInCluster getRoleInCluster() {
        return roleInCluster;
    }

    /**
     * Sets the value of the roleInCluster property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleInCluster }
     *     
     */
    public void setRoleInCluster(RoleInCluster value) {
        this.roleInCluster = value;
    }

    /**
     * Gets the value of the clusterProperties property.
     * 
     * @return
     *     possible object is
     *     {@link ClusterProperties }
     *     
     */
    public ClusterProperties getClusterProperties() {
        return clusterProperties;
    }

    /**
     * Sets the value of the clusterProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClusterProperties }
     *     
     */
    public void setClusterProperties(ClusterProperties value) {
        this.clusterProperties = value;
    }

    /**
     * Gets the value of the distanceMatrixType property.
     * 
     * @return
     *     possible object is
     *     {@link DistanceMatrixType }
     *     
     */
    public DistanceMatrixType getDistanceMatrixType() {
        return distanceMatrixType;
    }

    /**
     * Sets the value of the distanceMatrixType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistanceMatrixType }
     *     
     */
    public void setDistanceMatrixType(DistanceMatrixType value) {
        this.distanceMatrixType = value;
    }

    /**
     * Gets the value of the blastProperties property.
     * 
     * @return
     *     possible object is
     *     {@link BLASTProperties }
     *     
     */
    public BLASTProperties getBLASTProperties() {
        return blastProperties;
    }

    /**
     * Sets the value of the blastProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link BLASTProperties }
     *     
     */
    public void setBLASTProperties(BLASTProperties value) {
        this.blastProperties = value;
    }

    /**
     * Gets the value of the genomes property.
     * 
     * @return
     *     possible object is
     *     {@link Genomes }
     *     
     */
    public Genomes getGenomes() {
        return genomes;
    }

    /**
     * Sets the value of the genomes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Genomes }
     *     
     */
    public void setGenomes(Genomes value) {
        this.genomes = value;
    }

}
