//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.28 at 01:41:47 PM MSD 
//


package genblaster.properties.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "geneticTable",
    "additives"
})
@XmlRootElement(name = "Genome")
public class Genome {

    @XmlAttribute(name = "path", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String path;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "needs_check", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String needsCheck;
    @XmlElement(name = "GeneticTable", required = true)
    protected GeneticTable geneticTable;
    @XmlElement(name = "Additives", required = true)
    protected Additives additives;

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the needsCheck property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNeedsCheck() {
        return needsCheck;
    }

    /**
     * Sets the value of the needsCheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNeedsCheck(String value) {
        this.needsCheck = value;
    }

    /**
     * Gets the value of the geneticTable property.
     * 
     * @return
     *     possible object is
     *     {@link GeneticTable }
     *     
     */
    public GeneticTable getGeneticTable() {
        return geneticTable;
    }

    /**
     * Sets the value of the geneticTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneticTable }
     *     
     */
    public void setGeneticTable(GeneticTable value) {
        this.geneticTable = value;
    }

    /**
     * Gets the value of the additives property.
     * 
     * @return
     *     possible object is
     *     {@link Additives }
     *     
     */
    public Additives getAdditives() {
        return additives;
    }

    /**
     * Sets the value of the additives property.
     * 
     * @param value
     *     allowed object is
     *     {@link Additives }
     *     
     */
    public void setAdditives(Additives value) {
        this.additives = value;
    }

}
