//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.28 at 01:41:47 PM MSD 
//


package genblaster.properties.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the genblaster.properties.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: genblaster.properties.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Genomes }
     * 
     */
    public Genomes createGenomes() {
        return new Genomes();
    }

    /**
     * Create an instance of {@link Genome }
     * 
     */
    public Genome createGenome() {
        return new Genome();
    }

    /**
     * Create an instance of {@link ClusterSatellite }
     * 
     */
    public ClusterSatellite createClusterSatellite() {
        return new ClusterSatellite();
    }

    /**
     * Create an instance of {@link Additive }
     * 
     */
    public Additive createAdditive() {
        return new Additive();
    }

    /**
     * Create an instance of {@link DistanceMatrixType }
     * 
     */
    public DistanceMatrixType createDistanceMatrixType() {
        return new DistanceMatrixType();
    }

    /**
     * Create an instance of {@link ClusterSatellites }
     * 
     */
    public ClusterSatellites createClusterSatellites() {
        return new ClusterSatellites();
    }

    /**
     * Create an instance of {@link GeneticTable }
     * 
     */
    public GeneticTable createGeneticTable() {
        return new GeneticTable();
    }

    /**
     * Create an instance of {@link Additives }
     * 
     */
    public Additives createAdditives() {
        return new Additives();
    }

    /**
     * Create an instance of {@link SatelliteProperties }
     * 
     */
    public SatelliteProperties createSatelliteProperties() {
        return new SatelliteProperties();
    }

    /**
     * Create an instance of {@link UseCluster }
     * 
     */
    public UseCluster createUseCluster() {
        return new UseCluster();
    }

    /**
     * Create an instance of {@link RoleInCluster }
     * 
     */
    public RoleInCluster createRoleInCluster() {
        return new RoleInCluster();
    }

    /**
     * Create an instance of {@link GenBLASTerDbDir }
     * 
     */
    public GenBLASTerDbDir createGenBLASTerDbDir() {
        return new GenBLASTerDbDir();
    }

    /**
     * Create an instance of {@link AlterCodon }
     * 
     */
    public AlterCodon createAlterCodon() {
        return new AlterCodon();
    }

    /**
     * Create an instance of {@link MinORFLength }
     * 
     */
    public MinORFLength createMinORFLength() {
        return new MinORFLength();
    }

    /**
     * Create an instance of {@link BLASTProperties }
     * 
     */
    public BLASTProperties createBLASTProperties() {
        return new BLASTProperties();
    }

    /**
     * Create an instance of {@link Evalue }
     * 
     */
    public Evalue createEvalue() {
        return new Evalue();
    }

    /**
     * Create an instance of {@link SimultaniousBLASTs }
     * 
     */
    public SimultaniousBLASTs createSimultaniousBLASTs() {
        return new SimultaniousBLASTs();
    }

    /**
     * Create an instance of {@link MaxORFLength }
     * 
     */
    public MaxORFLength createMaxORFLength() {
        return new MaxORFLength();
    }

    /**
     * Create an instance of {@link ORFPool }
     * 
     */
    public ORFPool createORFPool() {
        return new ORFPool();
    }

    /**
     * Create an instance of {@link GenBLASTerHomeDir }
     * 
     */
    public GenBLASTerHomeDir createGenBLASTerHomeDir() {
        return new GenBLASTerHomeDir();
    }

    /**
     * Create an instance of {@link ClusterProperties }
     * 
     */
    public ClusterProperties createClusterProperties() {
        return new ClusterProperties();
    }

    /**
     * Create an instance of {@link GenBLASTerProperties }
     * 
     */
    public GenBLASTerProperties createGenBLASTerProperties() {
        return new GenBLASTerProperties();
    }

}
